# Generated by Django 3.0.8 on 2020-12-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_full_name', models.CharField(max_length=60)),
                ('User_username', models.CharField(max_length=70)),
                ('Image', models.ImageField(upload_to='Challenges/First/Users')),
                ('Video', models.FileField(upload_to='Challenges/First/Users')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
