# Generated by Django 3.0.8 on 2020-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_challenge',
            name='Image',
            field=models.ImageField(upload_to='Challenges/First/Users/<django.db.models.fields.CharField>-<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='first_challenge',
            name='Video',
            field=models.FileField(upload_to='Challenges/First/Users/<django.db.models.fields.CharField>-<django.db.models.fields.CharField>'),
        ),
    ]
