# Generated by Django 3.0.8 on 2020-12-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20201206_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_challenge',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Challenges/First/Users/'),
        ),
        migrations.AlterField(
            model_name='first_challenge',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='Challenges/First/Users/'),
        ),
    ]
