# Generated by Django 3.0.8 on 2020-12-06 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0005_first_challenge_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_full_name', models.CharField(max_length=60)),
                ('User_username', models.CharField(max_length=70)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Challenges/First/Users/')),
                ('Video', models.FileField(blank=True, null=True, upload_to='Challenges/First/Users/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='First_Challenge_2',
        ),
    ]
