# Generated by Django 3.0.8 on 2020-12-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20201206_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='User',
        ),
    ]
