# Generated by Django 3.0.8 on 2020-12-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_remove_mine_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mine',
        ),
        migrations.RemoveField(
            model_name='first_challenge',
            name='User',
        ),
    ]
