# Generated by Django 3.0.8 on 2020-12-06 22:13

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20201206_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_challenge',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=challenges.models.get_upload_path),
        ),
    ]
