# Generated by Django 3.0.8 on 2020-12-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20201206_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_challenge',
            name='Video',
        ),
    ]
