# Generated by Django 3.0.8 on 2020-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_remove_first_challenge_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_challenge',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='Challenges/First/Users'),
        ),
        migrations.AlterField(
            model_name='first_challenge',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='Challenges/First/Users/'),
        ),
    ]
