# Generated by Django 3.0.8 on 2020-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20201206_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_full_name', models.CharField(max_length=60)),
                ('User_username', models.CharField(max_length=70)),
                ('Image', models.FileField(blank=True, null=True, upload_to='Challenges/Second/Users/')),
                ('Video', models.FileField(blank=True, null=True, upload_to='Challenges/Second/Users')),
            ],
        ),
    ]
